repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-yaml
  - id: detect-private-key
  - id: trailing-whitespace
-   repo: git://github.com/detailyang/pre-commit-shell
    sha: 1.0.2
    hooks:
    -   id: shell-lint
