repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-yaml
  - id: detect-aws-credentials
  - id: detect-private-key
  - id: trailing-whitespace
