tap "homebrew/cask"
brew "aspell"
brew "git"
brew "mas"
brew "mtr"
brew "nmap"
brew "pre-commit"
brew "shellcheck"
brew "stow"
brew "ykman"
brew "ykpers"
brew "exercism"
cask 'gpg-suite'
cask 'homebrew/cask/emacs'
cask 'keybase'
cask 'muzzle'
cask 'signal'
cask 'wireshark'
cask 'secretive'
mas "1Blocker", id: 1107421413
mas "1Password 7", id: 1333542190
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Marked 2", id: 890031187
mas "Meeter", id: 1510445899
mas "Numbers", id: 409203825
mas "OmniFocus", id: 1346203938
mas "Pages", id: 409201541
mas "Soulver", id: 413965349
mas "The Unarchiver", id: 425424353
mas "WiFi Explorer", id: 494803304
